backend:
  name: git-gateway

#publish_mode: editorial_workflow

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: 'bike'
    label: 'Bike'
    folder: '_content/bike'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Type', name: 'type', widget: 'string' }
      - { label: 'Year', name: 'year', widget: 'string' }
      - { label: 'CC', name: 'cc', widget: 'string' }
      - { label: 'Mileage', name: 'mileage', widget: 'string' }
      - { label: 'Price', name: 'price', widget: 'string' }
      - { label: 'Description', name: 'body', widget: 'markdown' }